otiai10/copy

all_test.go
copy.go
go.mod
go.sum

In case someone wants to change file and directory permissions upon copying there's a new func `Perm(src, dest string, dirPerm, filePerm os.FileMode) error` which sets dirPerm for all copied directories and filePerfm for all copied files. 
I came upon the problem that in go modules loaded via `go get` files and directories have different permissions than in github. So I had to come up with this solution to be able to load from a template folder with the correct dest permissions independent from the src permissions.

Added Copy with requested Permissions

---

all_test.go
copy.go
options.go
testdata/case07/README.md
testdata/case07/dir_0500/README.md

Sometimes, we don't want to preserve the original permission of source entries. `Options.AddPermission` can add specific permission (e.g. `0200` = `--w-------`) to the original permission.
Example:
| - | - |
|:----|:-----|
| original | `dr-xr--r--` |
| options | `Options{AddPermission: 0200}` |
| results | `drwxr--r--` |

Add capability to add permission: Options.AddPermission

---

all_test.go
copy.go
example_test.go
go.sum
options.go

Hello!
Thank you for package. 
I faced to a problem when I need to copy all files with a specific extension, but then the Skip() function ignores directories.
Therefore, I propose such a small addition. Thank u!
P.S. Maybe you will rename a package so that it does not conflict with the standard copy function?

Skip by file info too

---

all_test.go
copy.go
testdata/case09/README.md

The test was covering `SymlinkAction==Deep`. However, the setup was using:
```
os.Symlink("testdata/case01", "testdata/case03/case01")
```
That creates a symlink to `testdata/case03/testdata/case01`, which does
not exists. Because the code was using only `os.Readlink`, the test
was passing blissfully.
Instead:
- Use `filepath.EvalSymlinks` to resolve the path completely.
- Use a relative link in the test.

Fix support for symlink deep copy.

---

all_test.go
copy.go

1. Check errors during test setup.
2. Create directories on the path to dest in `lcopy()`.

Fix small bug in lcopy and test setup

---

all_test.go
copy.go
fix_time_unix.go
fix_time_windows.go
go.mod
go.sum
options.go
testdata/case09/README.md
testdata/case09/symlink

The `PreserveTimes` option allows the copy to maintains the mtime and ctime of files and directory.

add PreserveTimes option

---

stat_times.go

I was having an issue with [probonopd/go-appimage](https;//github.com/probonopd/go-appimage) not building via TravisCI, particularly with GOARCH=386.

Fix for different GOARCHs

---

stat_times_darwin.go

Don't assume that Darwin is amd64-only.

Fix build on Apple Silicon

---

all_test.go
all_test_others.go
all_test_windows.go
copy.go
copy_others.go
copy_windows.go
test/data/case11/README.md

This prevents to hang while trying to open the file for reading. I've kept it simple to avoid any interface change, so should be good also for `v1`
The split into `_other` files was necessary since Windows doesn't support `syscall.Mkfifo`.
Fixes #47

Add support for named pipes

---

copy_namedpipes.go
copy_namedpipes_x.go
stat_times.go
stat_times_x.go
test_setup.go
test_setup_x.go

After  Preserved Time feature, is not possible build programs using this package in Plan9, NetBSD, AIX, Illumos and Solaris.
This change add build constrains to solved that and maintain the main feature: copy a directory.

Fix build in some OSes

---

copy.go

onsymlink get info from Lstat, info sent is never used.

Not send info to onsymlink

---

all_test.go
copy_namedpipes.go
copy_namedpipes_x.go
stat_times.go
stat_times_js.go
test_setup.go
test_setup_x.go

At present, this package does not work with WASM or GopherJS compile targets. See for example, the output from `go test` for WASM:
```
$ GOOS=js GOARCH=wasm go test ./... -exec=$(go env GOROOT)/misc/wasm/go_js_wasm_exec
./copy_namedpipes.go:16:9: undefined: syscall.Mkfifo
./stat_times.go:17:30: stat.Atim undefined (type *syscall.Stat_t has no field or method Atim)
./stat_times.go:18:30: stat.Ctim undefined (type *syscall.Stat_t has no field or method Ctim)
./test_setup.go:16:2: undefined: syscall.Mkfifo
FAIL    github.com/otiai10/copy [build failed]
FAIL
```
and GopherJS:
```
$ gopherjs test ./...
test_setup.go:16:10: Mkfifo not declared by package syscall
stat_times.go:17:31: stat.Atim undefined (type *syscall.Stat_t has no field or method Atim)
stat_times.go:17:53: stat.Atim undefined …
```

Make package work with WASM and GopherJS targets

---

all_test.go
copy.go
go.mod
go.sum
preserve_ltimes.go
preserve_ltimes_test.go
preserve_ltimes_x.go
preserve_ltimes_x_test.go
test/data/case15/README.md
test/data/case15/symlink

This is an addition to https://github.com/otiai10/copy/pull/31 - While symlink timestamps cannot be set universally (neither at time of link creation nor by a simple call to `os.Chtimes()`) they can be set on Unix making use of `unix.Lutimes()`. This PR extends the existing `PreserveTime` option by that, transferring the original link timestamp(s) to the newly created one if the option is set.
For unsupported architectures, a stub is provided similar to already existing ones (e.g. for ownership preservation).

Support PreserveTimes for symlinks on Unix

---

all_test.go
copy.go
options.go

Skip device files by default: Use opt.Specials

---

README.md
all_test.go
copy.go
example_test.go
options.go

[Breaking Change] Skip now accepts FileInfo

---

README.md
all_test.go
copy.go
options.go
test/data/case17/README.md

Please consider this.
This PR introduces `onErr` option in a form of `func(error)error` which lets caller to handler error cases .
It enables caller to log error by error and gives a possibility to continue with copying in case error is not that severe by returning nil (swallowing an error).

Let caller hander error cases

---

all_test.go
copy.go

This PR replaces the deprecated [io/ioutil](https://pkg.go.dev/io/ioutil) package with `os`:
- [`ioutil.ReadDir`](https://pkg.go.dev/io/ioutil#ReadDir) replaced with `os.ReadDir` and additional code to obtain a list of `fs.FileInfo` (the code is pointed out in the doc);
- [`ioutil.ReadFile`](https://pkg.go.dev/io/ioutil#ReadFile) replaced with `os.ReadFile`.

Replace deprecated 'io/ioutil' package with 'os'

---

copy_namedpipes.go
copy_namedpipes_x.go
patherror_test.go
preserve_ltimes.go
preserve_ltimes_test.go
preserve_ltimes_x.go
preserve_ltimes_x_test.go
preserve_owner.go
preserve_owner_x.go
stat_times.go
stat_times_darwin.go
stat_times_freebsd.go
stat_times_js.go
stat_times_windows.go
stat_times_x.go
symlink_test.go
symlink_test_x.go
test/images/alpine.Dockerfile
test_setup_test.go
test_setup_x_test.go

This PR removes outdated `// +build` build constraints. Use `go fix ./...` to remove the `// +build` lines that have become obsolete in Go 1.18. See https://go.dev/doc/go1.18#go-build-lines.
[Alpine 3.16](https://www.alpinelinux.org/posts/Alpine-3.16.0-released.html) is needed because it has Go 1.18.

Delete obsolete // +build lines

---

copy.go

Copy symlink if origin of the link doesn't exist

---

all_test.go
copy.go

Solves https://github.com/otiai10/copy/issues/132.
The behavior of `copy` by default is to overwrite files, i'm doing the same for symlinks here.

Overwrite symlink

---

all_test.go
copy.go
symlink_test.go
test_setup_test.go
test_setup_x_test.go

All relative paths of symbolic links should be resolved from the directory where the link is located. The current working directory does not affect the resolution of the path. A symbolic link can be absolute or relative, and may or may not have a leading dot. Directory content example:
```
file
symlink -> file
```
Copying of the directory with such content does not work currently. When copying `symlink`, `Copy` returns an error because the `file` does not exist in the current working directory. In the existing tests, there is a symbolic link named "symlink" that points to a file named "README.md". However, when resolving the path of the file, the file is located in the repository's root directory, not the test case directory, and copying of these dirs work fine.
The solution is to check …

Fix relative symlinks deep copying

---

.github/workflows/go.yml
copy.go
copy_methods.go
options.go

Implemented as discussed in #163 in [this comment](https://github.com/otiai10/copy/issues/163#issuecomment-2300899873).
A change was needed:
I have to check for the source file being deleted after the `FileCopyMethod` function is run.
- The old function returned `nil` if the source was deleted.
- When called from the refactored `fcopy`, it would think there was no error.
- `fcopy` would then try to apply changes to the destination file that was never made, then error.
I also had to change the CI so I could run workflows on my own repo. You can drop that commit before merging it.

feat: Add FileCopyMethod option / API
